const menu = [
    {
      id: 1,
      title: 'buttermilk pancakes',
      category: 'breakfast',
      price: 15.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5fL-k2lM6m83qZc3mwyH6XotwU5-7MJI9EgkDyAk0EAXvfQ9cFDu6umeDAJCpHOXPy7M&usqp=CAU',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 2,
      title: 'diner double',
      category: 'lunch',
      price: 13.99,
      img: 'https://b.zmtcdn.com/data/pictures/2/19281762/2c661ce4ac6e94c3bdd6055967a93825.jpg?fit=around|300:273&crop=300:273;*,*',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 3,
      title: 'godzilla milkshake',
      category: 'snacks',
      price: 6.99,
      img: 'https://media-cdn.tripadvisor.com/media/photo-s/11/e5/eb/0f/zooris-bar-restaurant.jpg',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 4,
      title: 'country delight',
      category: 'breakfast',
      price: 20.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkEujH1J6VKRCbhRLiTsWh-APTAo5nOcNS0bm6KMWWfJaucbgxx9RQ97rxhB6IafkEj1s&usqp=CAU',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 5,
      title: 'egg attack',
      category: 'lunch',
      price: 22.99,
      img: 'https://www.seafoodjunctiongoa.com/wp-content/uploads/2021/03/home09.jpg',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 6,
      title: 'oreo dream',
      category: 'snacks',
      price: 18.99,
      img: 'https://images.pexels.com/photos/1893555/pexels-photo-1893555.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 7,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      img: 'https://images.immediate.co.uk/production/volatile/sites/30/2013/05/Nutty-chicken-satay-a8c094e.jpg',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjRT3ghjsIW4UA9JvDUYuvNTSJgWdaEr8pqp6pc_dhpwV2cWZUPWbagd1ezXitVxd-sIM&usqp=CAU',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 9,
      title: 'quarantine buddy',
      category: 'snacks',
      price: 16.99,
      img: 'https://static.onecms.io/wp-content/uploads/sites/44/2019/08/26230809/6753430.jpg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 10,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjRT3ghjsIW4UA9JvDUYuvNTSJgWdaEr8pqp6pc_dhpwV2cWZUPWbagd1ezXitVxd-sIM&usqp=CAU',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 11,
      title: 'quarantine buddy',
      category: 'snacks',
      price: 16.99,
      img: 'https://static.onecms.io/wp-content/uploads/sites/44/2019/08/26230809/6753430.jpg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 12,
      title: 'egg attack',
      category: 'lunch',
      price: 22.99,
      img: 'https://www.seafoodjunctiongoa.com/wp-content/uploads/2021/03/home09.jpg',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 13,
      title: 'oreo dream',
      category: 'snacks',
      price: 18.99,
      img: 'https://images.pexels.com/photos/1893555/pexels-photo-1893555.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 14,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      img: 'https://images.immediate.co.uk/production/volatile/sites/30/2013/05/Nutty-chicken-satay-a8c094e.jpg',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 15,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjRT3ghjsIW4UA9JvDUYuvNTSJgWdaEr8pqp6pc_dhpwV2cWZUPWbagd1ezXitVxd-sIM&usqp=CAU',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 16,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjRT3ghjsIW4UA9JvDUYuvNTSJgWdaEr8pqp6pc_dhpwV2cWZUPWbagd1ezXitVxd-sIM&usqp=CAU',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 17,
      title: 'quarantine buddy',
      category: 'snacks',
      price: 16.99,
      img: 'https://static.onecms.io/wp-content/uploads/sites/44/2019/08/26230809/6753430.jpg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 18,
      title: 'egg attack',
      category: 'lunch',
      price: 22.99,
      img: 'https://www.seafoodjunctiongoa.com/wp-content/uploads/2021/03/home09.jpg',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 19,
      title: 'oreo dream',
      category: 'snacks',
      price: 18.99,
      img: 'https://images.pexels.com/photos/1893555/pexels-photo-1893555.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 20,
      title: 'buttermilk pancakes',
      category: 'breakfast',
      price: 15.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5fL-k2lM6m83qZc3mwyH6XotwU5-7MJI9EgkDyAk0EAXvfQ9cFDu6umeDAJCpHOXPy7M&usqp=CAU',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 21,
      title: 'diner double',
      category: 'lunch',
      price: 13.99,
      img: 'https://b.zmtcdn.com/data/pictures/2/19281762/2c661ce4ac6e94c3bdd6055967a93825.jpg?fit=around|300:273&crop=300:273;*,*',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 22,
      title: 'godzilla milkshake',
      category: 'snacks',
      price: 6.99,
      img: 'https://media-cdn.tripadvisor.com/media/photo-s/11/e5/eb/0f/zooris-bar-restaurant.jpg',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 23,
      title: 'country delight',
      category: 'breakfast',
      price: 20.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkEujH1J6VKRCbhRLiTsWh-APTAo5nOcNS0bm6KMWWfJaucbgxx9RQ97rxhB6IafkEj1s&usqp=CAU',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 24,
      title: 'egg attack',
      category: 'lunch',
      price: 22.99,
      img: 'https://www.seafoodjunctiongoa.com/wp-content/uploads/2021/03/home09.jpg',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 25,
      title: 'oreo dream',
      category: 'snacks',
      price: 18.99,
      img: 'https://images.pexels.com/photos/1893555/pexels-photo-1893555.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 26,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      img: 'https://images.immediate.co.uk/production/volatile/sites/30/2013/05/Nutty-chicken-satay-a8c094e.jpg',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 27,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjRT3ghjsIW4UA9JvDUYuvNTSJgWdaEr8pqp6pc_dhpwV2cWZUPWbagd1ezXitVxd-sIM&usqp=CAU',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 28,
      title: 'quarantine buddy',
      category: 'snacks',
      price: 16.99,
      img: 'https://static.onecms.io/wp-content/uploads/sites/44/2019/08/26230809/6753430.jpg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 29,
      title: 'egg attack',
      category: 'lunch',
      price: 22.99,
      img: 'https://www.seafoodjunctiongoa.com/wp-content/uploads/2021/03/home09.jpg',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 30,
      title: 'oreo dream',
      category: 'snacks',
      price: 18.99,
      img: 'https://images.pexels.com/photos/1893555/pexels-photo-1893555.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 31,
      title: 'buttermilk pancakes',
      category: 'breakfast',
      price: 15.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5fL-k2lM6m83qZc3mwyH6XotwU5-7MJI9EgkDyAk0EAXvfQ9cFDu6umeDAJCpHOXPy7M&usqp=CAU',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 32,
      title: 'diner double',
      category: 'lunch',
      price: 13.99,
      img: 'https://b.zmtcdn.com/data/pictures/2/19281762/2c661ce4ac6e94c3bdd6055967a93825.jpg?fit=around|300:273&crop=300:273;*,*',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 33,
      title: 'godzilla milkshake',
      category: 'snacks',
      price: 6.99,
      img: 'https://media-cdn.tripadvisor.com/media/photo-s/11/e5/eb/0f/zooris-bar-restaurant.jpg',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 34,
      title: 'oreo dream',
      category: 'snacks',
      price: 18.99,
      img: 'https://images.pexels.com/photos/1893555/pexels-photo-1893555.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 35,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      img: 'https://images.immediate.co.uk/production/volatile/sites/30/2013/05/Nutty-chicken-satay-a8c094e.jpg',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 36,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjRT3ghjsIW4UA9JvDUYuvNTSJgWdaEr8pqp6pc_dhpwV2cWZUPWbagd1ezXitVxd-sIM&usqp=CAU',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 37,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjRT3ghjsIW4UA9JvDUYuvNTSJgWdaEr8pqp6pc_dhpwV2cWZUPWbagd1ezXitVxd-sIM&usqp=CAU',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 38,
      title: 'quarantine buddy',
      category: 'snacks',
      price: 16.99,
      img: 'https://static.onecms.io/wp-content/uploads/sites/44/2019/08/26230809/6753430.jpg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 39,
      title: 'egg attack',
      category: 'lunch',
      price: 22.99,
      img: 'https://www.seafoodjunctiongoa.com/wp-content/uploads/2021/03/home09.jpg',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 40,
      title: 'oreo dream',
      category: 'snacks',
      price: 18.99,
      img: 'https://images.pexels.com/photos/1893555/pexels-photo-1893555.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 41,
      title: 'buttermilk pancakes',
      category: 'breakfast',
      price: 15.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5fL-k2lM6m83qZc3mwyH6XotwU5-7MJI9EgkDyAk0EAXvfQ9cFDu6umeDAJCpHOXPy7M&usqp=CAU',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 42,
      title: 'diner double',
      category: 'lunch',
      price: 13.99,
      img: 'https://b.zmtcdn.com/data/pictures/2/19281762/2c661ce4ac6e94c3bdd6055967a93825.jpg?fit=around|300:273&crop=300:273;*,*',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 43,
      title: 'godzilla milkshake',
      category: 'snacks',
      price: 6.99,
      img: 'https://media-cdn.tripadvisor.com/media/photo-s/11/e5/eb/0f/zooris-bar-restaurant.jpg',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 44,
      title: 'country delight',
      category: 'breakfast',
      price: 20.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkEujH1J6VKRCbhRLiTsWh-APTAo5nOcNS0bm6KMWWfJaucbgxx9RQ97rxhB6IafkEj1s&usqp=CAU',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 45,
      title: 'egg attack',
      category: 'lunch',
      price: 22.99,
      img: 'https://www.seafoodjunctiongoa.com/wp-content/uploads/2021/03/home09.jpg',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 46,
      title: 'oreo dream',
      category: 'snacks',
      price: 18.99,
      img: 'https://images.pexels.com/photos/1893555/pexels-photo-1893555.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 47,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      img: 'https://images.immediate.co.uk/production/volatile/sites/30/2013/05/Nutty-chicken-satay-a8c094e.jpg',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 48,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjRT3ghjsIW4UA9JvDUYuvNTSJgWdaEr8pqp6pc_dhpwV2cWZUPWbagd1ezXitVxd-sIM&usqp=CAU',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 49,
      title: 'quarantine buddy',
      category: 'snacks',
      price: 16.99,
      img: 'https://static.onecms.io/wp-content/uploads/sites/44/2019/08/26230809/6753430.jpg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 50,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjRT3ghjsIW4UA9JvDUYuvNTSJgWdaEr8pqp6pc_dhpwV2cWZUPWbagd1ezXitVxd-sIM&usqp=CAU',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 51,
      title: 'quarantine buddy',
      category: 'snacks',
      price: 16.99,
      img: 'https://static.onecms.io/wp-content/uploads/sites/44/2019/08/26230809/6753430.jpg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 52,
      title: 'egg attack',
      category: 'lunch',
      price: 22.99,
      img: 'https://www.seafoodjunctiongoa.com/wp-content/uploads/2021/03/home09.jpg',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 53,
      title: 'oreo dream',
      category: 'snacks',
      price: 18.99,
      img: 'https://images.pexels.com/photos/1893555/pexels-photo-1893555.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 54,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      img: 'https://images.immediate.co.uk/production/volatile/sites/30/2013/05/Nutty-chicken-satay-a8c094e.jpg',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 55,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjRT3ghjsIW4UA9JvDUYuvNTSJgWdaEr8pqp6pc_dhpwV2cWZUPWbagd1ezXitVxd-sIM&usqp=CAU',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 56,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjRT3ghjsIW4UA9JvDUYuvNTSJgWdaEr8pqp6pc_dhpwV2cWZUPWbagd1ezXitVxd-sIM&usqp=CAU',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 57,
      title: 'quarantine buddy',
      category: 'snacks',
      price: 16.99,
      img: 'https://static.onecms.io/wp-content/uploads/sites/44/2019/08/26230809/6753430.jpg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 58,
      title: 'egg attack',
      category: 'lunch',
      price: 22.99,
      img: 'https://www.seafoodjunctiongoa.com/wp-content/uploads/2021/03/home09.jpg',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 59,
      title: 'oreo dream',
      category: 'snacks',
      price: 18.99,
      img: 'https://images.pexels.com/photos/1893555/pexels-photo-1893555.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 60,
      title: 'buttermilk pancakes',
      category: 'breakfast',
      price: 15.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5fL-k2lM6m83qZc3mwyH6XotwU5-7MJI9EgkDyAk0EAXvfQ9cFDu6umeDAJCpHOXPy7M&usqp=CAU',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 61,
      title: 'diner double',
      category: 'lunch',
      price: 13.99,
      img: 'https://b.zmtcdn.com/data/pictures/2/19281762/2c661ce4ac6e94c3bdd6055967a93825.jpg?fit=around|300:273&crop=300:273;*,*',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 62,
      title: 'godzilla milkshake',
      category: 'snacks',
      price: 6.99,
      img: 'https://media-cdn.tripadvisor.com/media/photo-s/11/e5/eb/0f/zooris-bar-restaurant.jpg',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 63,
      title: 'country delight',
      category: 'breakfast',
      price: 20.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkEujH1J6VKRCbhRLiTsWh-APTAo5nOcNS0bm6KMWWfJaucbgxx9RQ97rxhB6IafkEj1s&usqp=CAU',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 64,
      title: 'egg attack',
      category: 'lunch',
      price: 22.99,
      img: 'https://www.seafoodjunctiongoa.com/wp-content/uploads/2021/03/home09.jpg',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 65,
      title: 'oreo dream',
      category: 'snacks',
      price: 18.99,
      img: 'https://images.pexels.com/photos/1893555/pexels-photo-1893555.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 66,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      img: 'https://images.immediate.co.uk/production/volatile/sites/30/2013/05/Nutty-chicken-satay-a8c094e.jpg',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 67,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjRT3ghjsIW4UA9JvDUYuvNTSJgWdaEr8pqp6pc_dhpwV2cWZUPWbagd1ezXitVxd-sIM&usqp=CAU',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 68,
      title: 'quarantine buddy',
      category: 'snacks',
      price: 16.99,
      img: 'https://static.onecms.io/wp-content/uploads/sites/44/2019/08/26230809/6753430.jpg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 69,
      title: 'egg attack',
      category: 'lunch',
      price: 22.99,
      img: 'https://www.seafoodjunctiongoa.com/wp-content/uploads/2021/03/home09.jpg',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 70,
      title: 'oreo dream',
      category: 'snacks',
      price: 18.99,
      img: 'https://images.pexels.com/photos/1893555/pexels-photo-1893555.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 71,
      title: 'buttermilk pancakes',
      category: 'breakfast',
      price: 15.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5fL-k2lM6m83qZc3mwyH6XotwU5-7MJI9EgkDyAk0EAXvfQ9cFDu6umeDAJCpHOXPy7M&usqp=CAU',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 72,
      title: 'diner double',
      category: 'lunch',
      price: 13.99,
      img: 'https://b.zmtcdn.com/data/pictures/2/19281762/2c661ce4ac6e94c3bdd6055967a93825.jpg?fit=around|300:273&crop=300:273;*,*',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 73,
      title: 'godzilla milkshake',
      category: 'snacks',
      price: 6.99,
      img: 'https://media-cdn.tripadvisor.com/media/photo-s/11/e5/eb/0f/zooris-bar-restaurant.jpg',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 74,
      title: 'oreo dream',
      category: 'snacks',
      price: 18.99,
      img: 'https://images.pexels.com/photos/1893555/pexels-photo-1893555.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 75,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      img: 'https://images.immediate.co.uk/production/volatile/sites/30/2013/05/Nutty-chicken-satay-a8c094e.jpg',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 76,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjRT3ghjsIW4UA9JvDUYuvNTSJgWdaEr8pqp6pc_dhpwV2cWZUPWbagd1ezXitVxd-sIM&usqp=CAU',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 77,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjRT3ghjsIW4UA9JvDUYuvNTSJgWdaEr8pqp6pc_dhpwV2cWZUPWbagd1ezXitVxd-sIM&usqp=CAU',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 78,
      title: 'quarantine buddy',
      category: 'snacks',
      price: 16.99,
      img: 'https://static.onecms.io/wp-content/uploads/sites/44/2019/08/26230809/6753430.jpg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    {
      id: 79,
      title: 'egg attack',
      category: 'lunch',
      price: 22.99,
      img: 'https://www.seafoodjunctiongoa.com/wp-content/uploads/2021/03/home09.jpg',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 80,
      title: 'oreo dream',
      category: 'snacks',
      price: 18.99,
      img: 'https://images.pexels.com/photos/1893555/pexels-photo-1893555.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
  ];
  export default menu;